avator_1:
 preparation: False # your can set it to False if you want to use the existing avator, it will save time
 bbox_shift: 5
 video_path: "data/video/ai_test_default_moving_vid.mp4"
 audio_clips:
     test_1: "data/audio/response-2.mpga"
 
  

